# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-mobile' do
 
  #use_frameworks!
  use_modular_headers!
  
  pod 'Alamofire', '~> 5.0'
  pod 'AlamofireImage', '~> 4.0'

end
.
